import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // next-env.d.ts is generated by Next.js on every build.
  { ignores: ['.next/**', 'node_modules/**', 'design-system/**', 'next-env.d.ts'] },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    // @react-pdf/renderer's <Image> draws into a PDF page. It is not an <img>
    // and has no alt attribute, so the image-alt rule does not apply here.
    files: ['src/components/pdf/**/*.tsx'],
    rules: { 'jsx-a11y/alt-text': 'off' },
  },
];

export default config;
