// Generated by evergif (https://github.com/ShreyasDasari/evergif).
// Re-run evergif to regenerate; CI runs this file as-is.
// Settings and steps live in the matching .web.json.
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createRequire } from 'node:module';

// require(), not a bare import: NODE_PATH and a globally installed
// playwright are invisible to ESM specifier resolution.
const { chromium } = createRequire(import.meta.url)('playwright');

const config = JSON.parse(
  await readFile(new URL(import.meta.url.replace(/\.mjs$/, '.json')), 'utf8'),
);
const transcript = [];

function visible(text) {
  return text.split('\n').map((line) => line.trim()).filter(Boolean)
    .slice(0, 40).join('\n');
}

const browser = await chromium.launch();
const context = await browser.newContext({
  viewport: config.viewport,
  recordVideo: { dir: config.videoDir, size: config.viewport },
  deviceScaleFactor: 1,
  reducedMotion: 'reduce',
  colorScheme: config.colorScheme,
});
const page = await context.newPage();

try {
  for (const step of config.steps) {
    switch (step.action) {
      case 'goto':
        // 'load', not 'networkidle': a dev server's HMR socket or any polling
        // request can keep the network busy forever. Follow goto with a wait.
        await page.goto(config.url + step.args[0], { waitUntil: 'load' });
        break;
      case 'click':
        await page.click(step.args[0]);
        break;
      case 'fill':
        await page.fill(step.args[0], step.args.slice(1).join(' '));
        break;
      case 'press':
        await page.keyboard.press(step.args[0]);
        break;
      case 'wait':
        await page.waitForSelector(step.args[0]);
        break;
      case 'scroll':
        await page.mouse.wheel(0, Number(step.args[0]));
        break;
      case 'pause':
        await page.waitForTimeout(Number(step.args[0]));
        break;
      default:
        throw new Error(`unknown step: ${step.action}`);
    }
    await page.waitForTimeout(config.pauseMs);
    transcript.push(`> ${step.raw}`);
    transcript.push(visible(await page.innerText('body')));
  }
} finally {
  const video = page.video();
  await context.close();
  await browser.close();
  if (video) {
    await mkdir(dirname(config.videoPath), { recursive: true });
    await rename(await video.path(), config.videoPath);
  }
  await writeFile(config.transcriptPath, transcript.join('\n') + '\n');
}

console.log(`evergif: recorded ${config.steps.length} steps to ${config.videoPath}`);
